import type { CategorieCard } from '../types/categorieCard'
import ecouteursf from '../assets/ecouteur-sf.png'
import montreJaune from '../assets/montre-jaune.png'
import pcPhlox from '../assets/pc-phlox.png'
import ps4 from '../assets/ps4.png'
import vrMan from '../assets/VRMan.png'
import bluetoophSpeaker from '../assets/bluetooph-speaker.png'

export const categorieCard: CategorieCard[] = [
  {
    title: 'earphone',
    subtitle: 'with',
    text: 'enjoy',
    image: ecouteursf,
    bgColor: 'bg-black',
    titleColor: 'text-neutral-600',
    subtitleColor: 'text-white',
    textColor: 'text-white',
    imageWidth: 'w-68 lg:w-100',
    imagePosition: 'bottom-0 right-0 lg:left-5',
    buttonColor: 'bg-red-500',
    buttonTextColor: 'text-white',
    buttonPadding: 'px-8 py-2',
    cardPadding: 'px-8 py-4 mt-5 lg:mt-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-1',
    cardHeight: 'lg:h-[420px]',
    itemsAlign: 'lg:items-stretch',
    justifyContent: 'lg:justify-center',
  },

  {
    title: 'gadget',
    subtitle: 'wear',
    text: 'new',
    image: montreJaune,
    bgColor: 'bg-yellow-400',
    titleColor: 'text-gray-100/40',
    subtitleColor: 'text-white',
    textColor: 'text-white',
    imageWidth: 'w-55 lg:w-80',
    imagePosition: 'bottom-30 right-4 lg:top-5 lg:left-15',
    buttonColor: 'bg-white',
    buttonTextColor: 'text-yellow-400',
    buttonPadding: 'px-8 py-2',
    cardPadding: 'px-8 py-4 mt-20 lg:mt-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-1',
    cardHeight: 'lg:h-[420px]',
    itemsAlign: 'lg:items-stretch',
    justifyContent: 'lg:justify-center',
  },

  {
    title: 'laptop',
    subtitle: 'device',
    text: 'trend',
    image: pcPhlox,
    bgColor: 'bg-red-500',
    titleColor: 'text-gray-100/40',
    subtitleColor: 'text-white',
    textColor: 'text-white',
    imageWidth: 'w-110',
    imagePosition: 'top-49 right-0 lg:top-40',
    buttonColor: 'bg-white',
    buttonTextColor: 'text-red-500',
    buttonPadding: 'px-20 py-2 lg:px-12',
    cardPadding: 'px-8 pt-4 pb-60 mt-20 lg:mt-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-2',
    cardHeight: 'lg:h-[420px]',
    itemsAlign: 'lg:items-stretch',
    justifyContent: 'lg:justify-start',
  },

  {
    title: 'console',
    subtitle: 'gaming',
    text: 'best',
    image: ps4,
    bgColor: 'bg-gray-700/40',
    titleColor: 'text-gray-200/50',
    subtitleColor: 'text-black',
    textColor: 'text-black',
    imageWidth: 'w-78',
    imagePosition: 'top-50 left-5 lg:top-5 lg:left-90',
    buttonColor: 'bg-red-500',
    buttonTextColor: 'text-white',
    buttonPadding: 'px-20 py-2 mt-2 lg:px-15',
    cardPadding: 'mt-10 px-8 pt-4 pb-70 mt-20 lg:mt-0 lg:pb-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-2',
    cardHeight: 'lg:h-[320px]',
    itemsAlign: 'lg:items-start',
    justifyContent: 'lg:justify-center',
  },

  {
    title: 'oculus',
    subtitle: 'game',
    text: 'play',
    image: vrMan,
    bgColor: 'bg-green-600',
    titleColor: 'text-gray-200/50',
    subtitleColor: 'text-white',
    textColor: 'text-white',
    imageWidth: 'w-110 lg:w-60',
    imagePosition: 'bottom-0 right-0',
    buttonColor: 'bg-white',
    buttonTextColor: 'text-green-600',
    buttonPadding: 'px-20 py-2 lg:px-10',
    cardPadding: 'px-8 pt-4 pb-70 mt-5 lg:mt-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-1',
    cardHeight: 'lg:h-[320px]',
    itemsAlign: 'lg:items-stretch',
    justifyContent: 'lg:justify-start',
    titleTextSize: 'lg:text-4xl',
  },

  {
    title: 'speaker',
    subtitle: 'amazone',
    text: 'new',
    image: bluetoophSpeaker,
    bgColor: 'bg-blue-600/90',
    titleColor: 'text-gray-200/60',
    subtitleColor: 'text-white',
    textColor: 'text-white',
    imageWidth: 'w-100 lg:w-60',
    imagePosition: 'bottom-0 left-20 lg:left-30',
    buttonColor: 'bg-white',
    buttonTextColor: 'text-blue-500',
    buttonPadding: 'px-20 py-2 lg:px-12',
    cardPadding: 'px-8 pt-4 pb-70 mt-5 lg:mt-0',
    gap: 'gap-2',
    colSpan: 'lg:col-span-1',
    cardHeight: 'lg:h-[320px]',
    itemsAlign: 'lg:items-stretch',
    justifyContent: 'lg:justify-start',
    titleTextSize: 'lg:text-4xl',
  },
]
